//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: app/src/main/java/com/example/notes/proto-schema/todoitem.proto

package notes;

@kotlin.jvm.JvmSynthetic
inline fun todoItem(block: notes.TodoItemKt.Dsl.() -> kotlin.Unit): notes.TodoItemProto.TodoItem =
  notes.TodoItemKt.Dsl._create(notes.TodoItemProto.TodoItem.newBuilder()).apply { block() }._build()
object TodoItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: notes.TodoItemProto.TodoItem.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: notes.TodoItemProto.TodoItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): notes.TodoItemProto.TodoItem = _builder.build()

    /**
     * <code>string title = 1;</code>
     */
    var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * <code>string title = 1;</code>
     */
    fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * <code>string details = 2;</code>
     */
    var details: kotlin.String
      @JvmName("getDetails")
      get() = _builder.getDetails()
      @JvmName("setDetails")
      set(value) {
        _builder.setDetails(value)
      }
    /**
     * <code>string details = 2;</code>
     */
    fun clearDetails() {
      _builder.clearDetails()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun notes.TodoItemProto.TodoItem.copy(block: notes.TodoItemKt.Dsl.() -> kotlin.Unit): notes.TodoItemProto.TodoItem =
  notes.TodoItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()
