//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: app/src/main/java/com/example/notes/proto-schema/todoitem.proto
//
package notes;
//
//public final class TodoItemProto {
//  private TodoItemProto() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface TodoItemOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:notes.TodoItem)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>string title = 1;</code>
//     * @return The title.
//     */
//    java.lang.String getTitle();
//    /**
//     * <code>string title = 1;</code>
//     * @return The bytes for title.
//     */
//    com.google.protobuf.ByteString
//        getTitleBytes();
//
//    /**
//     * <code>string details = 2;</code>
//     * @return The details.
//     */
//    java.lang.String getDetails();
//    /**
//     * <code>string details = 2;</code>
//     * @return The bytes for details.
//     */
//    com.google.protobuf.ByteString
//        getDetailsBytes();
//  }
//  /**
//   * Protobuf type {@code notes.TodoItem}
//   */
//  public static final class TodoItem extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:notes.TodoItem)
//      TodoItemOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use TodoItem.newBuilder() to construct.
//    private TodoItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private TodoItem() {
//      title_ = "";
//      details_ = "";
//    }
//
//    @java.lang.Override
//    @SuppressWarnings({"unused"})
//    protected java.lang.Object newInstance(
//        UnusedPrivateParameter unused) {
//      return new TodoItem();
//    }
//
//    @java.lang.Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private TodoItem(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      if (extensionRegistry == null) {
//        throw new java.lang.NullPointerException();
//      }
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            case 10: {
//              java.lang.String s = input.readStringRequireUtf8();
//
//              title_ = s;
//              break;
//            }
//            case 18: {
//              java.lang.String s = input.readStringRequireUtf8();
//
//              details_ = s;
//              break;
//            }
//            default: {
//              if (!parseUnknownField(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return notes.TodoItemProto.internal_static_notes_TodoItem_descriptor;
//    }
//
//    @java.lang.Override
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return notes.TodoItemProto.internal_static_notes_TodoItem_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              notes.TodoItemProto.TodoItem.class, notes.TodoItemProto.TodoItem.Builder.class);
//    }
//
//    public static final int TITLE_FIELD_NUMBER = 1;
//    private volatile java.lang.Object title_;
//    /**
//     * <code>string title = 1;</code>
//     * @return The title.
//     */
//    @java.lang.Override
//    public java.lang.String getTitle() {
//      java.lang.Object ref = title_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        title_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string title = 1;</code>
//     * @return The bytes for title.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getTitleBytes() {
//      java.lang.Object ref = title_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        title_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int DETAILS_FIELD_NUMBER = 2;
//    private volatile java.lang.Object details_;
//    /**
//     * <code>string details = 2;</code>
//     * @return The details.
//     */
//    @java.lang.Override
//    public java.lang.String getDetails() {
//      java.lang.Object ref = details_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        details_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string details = 2;</code>
//     * @return The bytes for details.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getDetailsBytes() {
//      java.lang.Object ref = details_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        details_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @java.lang.Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @java.lang.Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
//      }
//      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(details_)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, details_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    @java.lang.Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
//      }
//      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(details_)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, details_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @java.lang.Override
//    public boolean equals(final java.lang.Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof notes.TodoItemProto.TodoItem)) {
//        return super.equals(obj);
//      }
//      notes.TodoItemProto.TodoItem other = (notes.TodoItemProto.TodoItem) obj;
//
//      if (!getTitle()
//          .equals(other.getTitle())) return false;
//      if (!getDetails()
//          .equals(other.getDetails())) return false;
//      if (!unknownFields.equals(other.unknownFields)) return false;
//      return true;
//    }
//
//    @java.lang.Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + TITLE_FIELD_NUMBER;
//      hash = (53 * hash) + getTitle().hashCode();
//      hash = (37 * hash) + DETAILS_FIELD_NUMBER;
//      hash = (53 * hash) + getDetails().hashCode();
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static notes.TodoItemProto.TodoItem parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static notes.TodoItemProto.TodoItem parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static notes.TodoItemProto.TodoItem parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static notes.TodoItemProto.TodoItem parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @java.lang.Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(notes.TodoItemProto.TodoItem prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @java.lang.Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code notes.TodoItem}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:notes.TodoItem)
//        notes.TodoItemProto.TodoItemOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return notes.TodoItemProto.internal_static_notes_TodoItem_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return notes.TodoItemProto.internal_static_notes_TodoItem_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                notes.TodoItemProto.TodoItem.class, notes.TodoItemProto.TodoItem.Builder.class);
//      }
//
//      // Construct using notes.TodoItemProto.TodoItem.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        title_ = "";
//
//        details_ = "";
//
//        return this;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return notes.TodoItemProto.internal_static_notes_TodoItem_descriptor;
//      }
//
//      @java.lang.Override
//      public notes.TodoItemProto.TodoItem getDefaultInstanceForType() {
//        return notes.TodoItemProto.TodoItem.getDefaultInstance();
//      }
//
//      @java.lang.Override
//      public notes.TodoItemProto.TodoItem build() {
//        notes.TodoItemProto.TodoItem result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @java.lang.Override
//      public notes.TodoItemProto.TodoItem buildPartial() {
//        notes.TodoItemProto.TodoItem result = new notes.TodoItemProto.TodoItem(this);
//        result.title_ = title_;
//        result.details_ = details_;
//        onBuilt();
//        return result;
//      }
//
//      @java.lang.Override
//      public Builder clone() {
//        return super.clone();
//      }
//      @java.lang.Override
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return super.setField(field, value);
//      }
//      @java.lang.Override
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return super.clearField(field);
//      }
//      @java.lang.Override
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return super.clearOneof(oneof);
//      }
//      @java.lang.Override
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, java.lang.Object value) {
//        return super.setRepeatedField(field, index, value);
//      }
//      @java.lang.Override
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return super.addRepeatedField(field, value);
//      }
//      @java.lang.Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof notes.TodoItemProto.TodoItem) {
//          return mergeFrom((notes.TodoItemProto.TodoItem)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(notes.TodoItemProto.TodoItem other) {
//        if (other == notes.TodoItemProto.TodoItem.getDefaultInstance()) return this;
//        if (!other.getTitle().isEmpty()) {
//          title_ = other.title_;
//          onChanged();
//        }
//        if (!other.getDetails().isEmpty()) {
//          details_ = other.details_;
//          onChanged();
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      @java.lang.Override
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        notes.TodoItemProto.TodoItem parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (notes.TodoItemProto.TodoItem) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//
//      private java.lang.Object title_ = "";
//      /**
//       * <code>string title = 1;</code>
//       * @return The title.
//       */
//      public java.lang.String getTitle() {
//        java.lang.Object ref = title_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          title_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string title = 1;</code>
//       * @return The bytes for title.
//       */
//      public com.google.protobuf.ByteString
//          getTitleBytes() {
//        java.lang.Object ref = title_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          title_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string title = 1;</code>
//       * @param value The title to set.
//       * @return This builder for chaining.
//       */
//      public Builder setTitle(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        title_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string title = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearTitle() {
//
//        title_ = getDefaultInstance().getTitle();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string title = 1;</code>
//       * @param value The bytes for title to set.
//       * @return This builder for chaining.
//       */
//      public Builder setTitleBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        title_ = value;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object details_ = "";
//      /**
//       * <code>string details = 2;</code>
//       * @return The details.
//       */
//      public java.lang.String getDetails() {
//        java.lang.Object ref = details_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          details_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string details = 2;</code>
//       * @return The bytes for details.
//       */
//      public com.google.protobuf.ByteString
//          getDetailsBytes() {
//        java.lang.Object ref = details_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          details_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string details = 2;</code>
//       * @param value The details to set.
//       * @return This builder for chaining.
//       */
//      public Builder setDetails(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        details_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string details = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearDetails() {
//
//        details_ = getDefaultInstance().getDetails();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string details = 2;</code>
//       * @param value The bytes for details to set.
//       * @return This builder for chaining.
//       */
//      public Builder setDetailsBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        details_ = value;
//        onChanged();
//        return this;
//      }
//      @java.lang.Override
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      @java.lang.Override
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:notes.TodoItem)
//    }
//
//    // @@protoc_insertion_point(class_scope:notes.TodoItem)
//    private static final notes.TodoItemProto.TodoItem DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new notes.TodoItemProto.TodoItem();
//    }
//
//    public static notes.TodoItemProto.TodoItem getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<TodoItem>
//        PARSER = new com.google.protobuf.AbstractParser<TodoItem>() {
//      @java.lang.Override
//      public TodoItem parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new TodoItem(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<TodoItem> parser() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<TodoItem> getParserForType() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public notes.TodoItemProto.TodoItem getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_notes_TodoItem_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_notes_TodoItem_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n?app/src/main/java/com/example/notes/pr" +
//      "oto-schema/todoitem.proto\022\005notes\"*\n\010Todo" +
//      "Item\022\r\n\005title\030\001 \001(\t\022\017\n\007details\030\002 \001(\tB\017B\r" +
//      "TodoItemProtob\006proto3"
//    };
//    descriptor = com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        });
//    internal_static_notes_TodoItem_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_notes_TodoItem_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_notes_TodoItem_descriptor,
//        new java.lang.String[] { "Title", "Details", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
